config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'

  resources :projects
  resources :tickets

  
  resources :tags, only: [:new, :edit, :destroy]
  get 'tags', to: 'tags#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:create, :edit, :update, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tickets, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  belongs_to :user
  
  def open_tickets
    self.tickets.select do |t|
     ['new', 'blocked', 'in_progress'].include?(t.status) 
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags_tickets
  has_many :tickets, through: :tags_tickets

  scope :with_counts, -> {
      left_outer_joins(:taggings).select("tags.*, COUNT(taggings.id)").
        group("tags.id")
    }

  scope :alphabetical, -> { order("tags.name ASC") }
end

app/models/tags_ticket.rb
class TagsTicket < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :tag
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_many :tags_tickets, dependent: :destroy
  has_many :tags, through: :tags_tickets
  
  STATUSES = %w(new blocked in_progress fixed)
  validates :status, inclusion: { in: STATUSES,
    message: "Status must be either 'new', 'blocked', 'in_progress' or 'fixed" }

  def add_tags(tags)
    tags.each do |tag_id|
      self.tags << Tag.find(tag_id) if !tag_id.empty?
    end
  end

  def has_tag?(tag_id)
    self.tags.map { |t| t.id }.include?(tag_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :tickets

  has_secure_password validations: false
  
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  
  def index

  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Your project was created.'
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Your project was updated.'
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = 'Your project was deleted.'
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base
  def new; end

  def create
    user = User.where(name: params[:name]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to root_path
    else
      flash.now[:error] = "There is something wrong with your username and password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class Tag < ApplicationController
  before_action :require_user, except: [:index]
  
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]

  def index
    @tickets = Ticket.all
    @tickets = @tickets.select { |t| t.project_id == params[:project].to_i } if exists?(:project)
    @tickets = @tickets.select { |t| t.status == params[:status] } if exists?(:status)
    @tickets = @tickets.select { |t| t.has_tag?(params[:tag].to_i) } if exists?(:tag)
  end

  def show; end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      @ticket.add_tags(params[:ticket][:tag_ids])
      flash[:notice] = 'Your ticket was created.'
      redirect_to root_path
    else
      render :new
    end
  end

  
  def edit; end

  def update
    if @ticket.update(ticket_params)
      @ticket.add_tags(params[:ticket][:tag_ids])
      flash[:notice] = 'Ticket was updated.'
      redirect_to '/tickets'
    else
      render :update
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = 'Your ticket was deleted.'
    redirect_back(fallback_location: root_path)
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:project_id, :status, :name, :body)
  end

  def exists?(parameter)
    params[parameter] && !params[parameter].empty?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:id] = @user.id
      flash[:notice] = "You have signed up."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <div id="flash_#{name}"><%= msg %></div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
  <ul class='left'>
    <li>Ticketing </li>
    <li><%= link_to 'Projects', projects_path %></li>
    <li><%= link_to 'Tickets', tickets_path %></li>
  </ul>
  <ul class='right'>
    <li>
      <% if logged_in? %>
        <%= link_to 'Logout', logout_path %>
      <% else %>
        <%= link_to 'Login', login_path %>
        or
        <%= link_to 'Signup', new_user_path  %>
      <% end %>
    </li>
  </ul>
  <div class='clear'></div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Counter</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
       <%= render 'layouts/navigation' %>
       <%= render 'layouts/messages' %>
    </header>
    <main>
       <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<div>
  <%= form_for @project do |f| %>
  <%= render 'shared/errors', obj: @project %>
    <dl>
      <dt><%= f.label :name %></dt>
      <dd><%= f.text_field :name %></dd>
      <dt><%= f.label :description %></dt>
      <dd><%= f.text_area :description %></dd>
    </dl>
    <%= f.submit (@project.new_record? ? 'Create' : 'Update'), class: 'btn' %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<%= render 'shared/title', title: "Edit >> #{@project.name}" %>

<%= render 'form' %>

app/views/projects/index.html.erb
<%= render 'shared/title', title: 'Projects' %>
<table>
 <thead>
   <tr>
     <th>Name</th>
     <th>Open Tickets</th>
     <th>Total Tickets</th>
   </tr>
 </thead>
 <tbody>
     <% Project.all.each do |project| %>
        <tr>
          <td>
            <strong><%= link_to project.name, project_path(project) %></strong>
            <br/>
            <%= project.description %>
          </td>
          <td><%= project.open_tickets.size %></td>
          <td><%= project.tickets.size %></td>
        </tr>
     <% end %>
 </tbody>
</table>

<% if logged_in? %>
  <%= link_to 'New Project', new_project_path, class: 'nav-link' %>
<% end %>

app/views/projects/new.html.erb
<%= render 'shared/title', title: "Create a Project" %>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= render 'shared/title', title: "#{@project.name}" %>

<p>
  <%= @project. description %>
</p>

<% if logged_in? %>
  <p>
    <%= link_to 'Edit Project', edit_project_path(@project) %>
    <%= link_to 'Delete Project', project_path(@project),
        method: :delete,
        data: { confirm: 'Are you sure?' } 
    %>
  </p>
<% end %>

<%= render 'tickets/tickets', tickets: @project.tickets, show_name: true %>

<% if logged_in? %>
  <%= link_to 'New Ticket', new_ticket_path(@project), class: 'nav-link' %>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8'>
      <h5> There were some errors: </h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/shared/_tags.html.erb
<% if tags.size > 0 %>
  <% tags.uniq.each do |tag| %>
    <em><%= tag.name %></em>,
  <% end %>
<% else %>
-
<% end %>

app/views/shared/_title.html.erb
<h1><%= title %></h1>

app/views/tickets/_form.html.erb
<div>
  <%= form_for @ticket do |f| %>
  <%= render 'shared/errors', obj: @ticket %>
    <%= f.label :project %>
    <%= f.collection_select :project_id, Project.all, :id, :name, id: :ticket_project_id  %>
    <%= f.label :status %>
    <%= f.select :status, Ticket::STATUSES.map{|t| [t, t]}, id: :ticket_status %>
    <dl>
      <dt><%= f.label :name %></dt>
      <dd><%= f.text_field :name %></dd>
      <dt><%= f.label :body %></dt>
      <dd><%= f.text_area :body %></dd>
      <dt><%= f.label :tags %></dt>
      <dd><%= f.collection_select :tag_ids, Tag.alphabetical, :id, :name, {}, multiple: true, id: :ticket_tag_ids, size: Tag.count %></dd>
    </dl>

    <!-- TODO: add assigned to -->
    <%= f.submit (@ticket.new_record? ? 'Create Ticket' : 'Update Ticket'), class: 'btn' %>
  <% end %>
</div>

app/views/tickets/_ticket.html.erb
<% show_name ||= false %>
<tr>
  <% if show_name %>
    <td>
      <strong><%= link_to ticket.name, ticket_path(ticket) %></strong>
    </td>
    <td><!-- ticket.assignee  --></td>
  <% else %>
    <!-- TODO: add creator -->
    <td></td>
  <% end %>
  <td><%= ticket.status %></td>
  <td>
    <%= render 'shared/tags', tags: ticket.tags %>
  </td>
  <% if logged_in? %>
    <td>
      <%= link_to 'Edit', edit_ticket_path(ticket) %>
      <%= link_to 'Delete', ticket_path(ticket),
          method: :delete,
          data: { confirm: 'Are you sure?' } 
      %>
    </td>
  <% end %>
</tr>

app/views/tickets/_tickets.html.erb
<% show_name ||= false %>



 <% if tickets.empty? %>
<p>There are no tickets matching the selected criteria.</p>

 <% else %>
    <table>
        <thead>
           <tr>
             <% if show_name %>
                <th>Name</th>
                <th>Assignee</th>
             <% else %>
                <th>Creator</th>
             <% end %>
                 <th>Status</th>
                 <th>Tags</th>
                 <% if logged_in? %>
                    <th></th>
                <% end %>
           </tr>
        </thead>
        <tbody>
            <% tickets.each do |ticket| %>
                <%= render 'tickets/ticket', ticket: ticket, show_name: show_name %>
            <% end %>
        </tbody>
    </table>
 <% end %>

app/views/tickets/edit.html.erb
<%= render 'shared/title', title: 'Edit Ticket' %>

<%= render 'form' %>

app/views/tickets/index.html.erb
<%= render 'shared/title', title: 'Tickets' %>

<div class='filter-tickets'>
  <%= form_tag tickets_path, method: :get, enforce_utf8: false do %>
    <p>
      Show tickets from 
      <%= select_tag :project, options_from_collection_for_select(Project.all, :id, :name, params[:project]), include_blank: "All Projects" %> 
      with status
      <%= select_tag :status, options_for_select(Ticket::STATUSES.map{|t| [t.titleize, t]}, params[:status]), include_blank: "Any Status" %>
      tagged
      <%= select_tag :tag, options_from_collection_for_select(Tag.alphabetical, :id, :name, params[:tag]), include_blank: "-" %>

      <%= button_tag "Update", name: nil %>
      <span class="reset">
        <%= link_to "Clear Filters", '/tickets' %>
      </p>
    </p>
  <% end %>
</div>


<%= render 'tickets/tickets', tickets: @tickets, show_name: true %>

<% if logged_in? %>
  <%= link_to 'New Ticket', new_ticket_path, class: 'nav-link' %>
<% end %>

app/views/tickets/new.html.erb
<%= render 'shared/title', title: 'New Ticket' %>

<%= render 'form' %>

app/views/tickets/show.html.erb
<%= render 'shared/title', title: @ticket.name %>

<p>
  <%= @ticket.body %>
</p>
<p>
  <strong>Tags:</strong>
  <%= render 'shared/tags', tags: @ticket.tags %>
</p>
<% if logged_in? %>
  <%= link_to 'Edit Ticket', edit_ticket_path(@ticket), class: 'nav-link' %>
<% end %>
<%= render 'tickets/tickets', tickets: [@ticket], show_name: false %>

app/views/users/new.html.erb
<%= render 'shared/title', title: 'Sign up' %>

<%= form_for @user do |f| %>
  <%= render 'shared/errors', obj: @user %>
  <dl>
    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>
    <dt><%= f.label :password %></dt>
    <dd><%= f.password_field :password %></dd>
  </dl>
  <%= f.submit "Sign up", class: 'btn' %>
<% end %>